---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "blog-chart.fullname" . }}
  labels:
    {{- include "blog-chart.labels" . | nindent 4 }}
data:
  {{ (.Files.Glob "files/env").AsConfig | indent 2 }}
